spring.application.name=NubeSandovalAPI

# ==============================
# Redis
# ==============================
spring.data.redis.repositories.enabled=false

# ===============================
# MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/nube_sandoval?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=josesas
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

storage.base-path=/media/josesas/KINGSTON

# ==============================
# MULTIPART (UPLOAD)
# ==============================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
